[package]
authors = ["Alexandra Frydl <me@alexfrydl.com>"]
description = "Macros for the indigo crate."
edition = "2018"
license = "MPL-2.0"
name = "indigo-macros"
version = "0.2.0-pre"

[package.metadata.docs.rs]
all-features = true

[lib]
